# -*- coding: utf-8 -*-
"""Thomas Ramirez Villa - PlantillaBacktracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HRxVJHtRSvTjuN3da8X-viQ52LKI0V9

# Plantilla doble de Backtracking  
## GuardianPass + ROVER-5

**Curso:** Introducción a las Ciencias de la Computación  
**Tema:** Backtracking y aplicaciones en ciencias de la computación  

Idea central:

$
\text{Explorar posibilidades, usar restricciones y retroceder con inteligencia.}
$

Este notebook contiene **dos ejemplos resueltos**:

1. **GuardianPass:** generar contraseñas válidas bajo reglas simples.  
2. **ROVER-5:** encontrar un camino en una grilla con obstáculos.

La intención no es que los grupos copien estos ejemplos literalmente, sino que usen la estructura como plantilla para sus propios proyectos: representación, candidatos, restricciones, poda, recursión, pruebas y reflexión.

# Parte I — GuardianPass  
## Contraseñas válidas sin ensayo ciego

GuardianPass es una plataforma educativa en pruebas. El equipo necesita generar contraseñas que cumplan una política simple: longitud fija, al menos una mayúscula, una minúscula, un dígito y un símbolo.

No vamos a romper contraseñas reales ni conectarnos a ningún sistema. Este es un ejercicio local y controlado para entender cómo backtracking construye cadenas válidas carácter por carácter.

## 1. Modelamiento con backtracking

| Elemento | En GuardianPass |
|---|---|
| Solución parcial | Lista de caracteres elegidos hasta el momento |
| Candidatos | Letras, dígitos y símbolos permitidos |
| Restricciones | Longitud, categorías obligatorias, no repetición, palabras prohibidas |
| Solución completa | Contraseña de longitud fija que cumple todas las reglas |
| Retroceso | Quitar el último carácter cuando una rama no sirve |
| Poda | Descartar ramas donde ya no sea posible cumplir las categorías faltantes |

Ejemplo de solución parcial:

```python
["A", "b", "3"]
```

Todavía no es una contraseña completa, pero ya podemos revisar algunas restricciones.

## 2. Datos de ejemplo

Usaremos conjuntos pequeños para que el árbol de búsqueda sea entendible.
"""

mayusculas = ["A", "B", "C"]
minusculas = ["a", "b", "c"]
digitos = ["1", "2", "3"]
simbolos = ["!", "#"]

caracteres_permitidos = mayusculas + minusculas + digitos + simbolos

politica = {
    "longitud": 5,
    "requiere_mayuscula": True,
    "requiere_minuscula": True,
    "requiere_digito": True,
    "requiere_simbolo": True,
    "no_repetir": True,
    "palabras_prohibidas": ["abc", "123", "pass"]
}

print("Caracteres permitidos:", caracteres_permitidos)
print("Política:", politica)

"""## 3. Funciones auxiliares

Primero escribimos funciones pequeñas para verificar categorías y restricciones.

"""

def contiene_mayuscula(cadena):
    return any(c in mayusculas for c in cadena)

def contiene_minuscula(cadena):
    return any(c in minusculas for c in cadena)

def contiene_digito(cadena):
    return any(c in digitos for c in cadena)

def contiene_simbolo(cadena):
    return any(c in simbolos for c in cadena)

def contiene_palabra_prohibida(cadena, palabras_prohibidas):
    texto = "".join(cadena).lower()
    return any(palabra.lower() in texto for palabra in palabras_prohibidas)

def categorias_faltantes(cadena, politica):
    faltantes = 0

    if politica["requiere_mayuscula"] and not contiene_mayuscula(cadena):
        faltantes += 1

    if politica["requiere_minuscula"] and not contiene_minuscula(cadena):
        faltantes += 1

    if politica["requiere_digito"] and not contiene_digito(cadena):
        faltantes += 1

    if politica["requiere_simbolo"] and not contiene_simbolo(cadena):
        faltantes += 1

    return faltantes

def es_contrasena_completa_valida(cadena, politica):
    if len(cadena) != politica["longitud"]:
        return False

    if politica["requiere_mayuscula"] and not contiene_mayuscula(cadena):
        return False

    if politica["requiere_minuscula"] and not contiene_minuscula(cadena):
        return False

    if politica["requiere_digito"] and not contiene_digito(cadena):
        return False

    if politica["requiere_simbolo"] and not contiene_simbolo(cadena):
        return False

    if contiene_palabra_prohibida(cadena, politica["palabras_prohibidas"]):
        return False

    return True

def es_candidato_valido(cadena_actual, candidato, politica):
    if politica["no_repetir"] and candidato in cadena_actual:
        return False

    nueva = cadena_actual + [candidato]

    if contiene_palabra_prohibida(nueva, politica["palabras_prohibidas"]):
        return False

    if len(nueva) > politica["longitud"]:
        return False

    return True

def debe_podar(cadena_actual, politica):
    posiciones_restantes = politica["longitud"] - len(cadena_actual)
    faltantes = categorias_faltantes(cadena_actual, politica)

    # Si faltan más categorías obligatorias que posiciones disponibles,
    # esta rama ya no puede producir una contraseña válida.
    return faltantes > posiciones_restantes

print("Categorías faltantes en ['A', 'b']:", categorias_faltantes(["A", "b"], politica))

"""## 4. Backtracking para generar contraseñas

La función construye la contraseña carácter por carácter.

Contadores:

- `llamadas_recursivas`: cuántas veces entramos a la función.
- `ramas_descartadas`: candidatos rechazados por restricciones o poda.
- `retrocesos`: cuántas veces deshacemos una decisión.

"""

def generar_contrasenas(politica, limite=10):
    soluciones = []

    estadisticas = {
        "llamadas_recursivas": 0,
        "ramas_descartadas": 0,
        "retrocesos": 0
    }

    def backtracking(cadena_actual):
        estadisticas["llamadas_recursivas"] += 1

        # Si ya tenemos suficientes soluciones, detenemos la búsqueda.
        if len(soluciones) >= limite:
            return

        # Poda sobre la solución parcial.
        if debe_podar(cadena_actual, politica):
            estadisticas["ramas_descartadas"] += 1
            return

        # Caso base: la cadena ya tiene longitud completa.
        if len(cadena_actual) == politica["longitud"]:
            if es_contrasena_completa_valida(cadena_actual, politica):
                soluciones.append("".join(cadena_actual))
            else:
                estadisticas["ramas_descartadas"] += 1
            return

        # Probar candidatos.
        for candidato in caracteres_permitidos:
            if es_candidato_valido(cadena_actual, candidato, politica):
                cadena_actual.append(candidato)

                backtracking(cadena_actual)

                # Retroceso: deshacer la decisión.
                cadena_actual.pop()
                estadisticas["retrocesos"] += 1
            else:
                estadisticas["ramas_descartadas"] += 1

    backtracking([])
    return soluciones, estadisticas


soluciones, stats = generar_contrasenas(politica, limite=10)

print("Contraseñas generadas:")
for s in soluciones:
    print("-", s)

print("\nEstadísticas:")
print(stats)

"""## 5. Pruebas de GuardianPass

Probemos varias políticas. En un proyecto real, no basta con mostrar un solo caso que funciona.

"""

politica_mas_corta = {
    "longitud": 4,
    "requiere_mayuscula": True,
    "requiere_minuscula": True,
    "requiere_digito": True,
    "requiere_simbolo": True,
    "no_repetir": True,
    "palabras_prohibidas": ["abc", "123", "pass"]
}

politica_sin_simbolo = {
    "longitud": 4,
    "requiere_mayuscula": True,
    "requiere_minuscula": True,
    "requiere_digito": True,
    "requiere_simbolo": False,
    "no_repetir": True,
    "palabras_prohibidas": ["abc", "123", "pass"]
}

politica_imposible = {
    "longitud": 3,
    "requiere_mayuscula": True,
    "requiere_minuscula": True,
    "requiere_digito": True,
    "requiere_simbolo": True,
    "no_repetir": True,
    "palabras_prohibidas": ["abc", "123", "pass"]
}

casos_guardianpass = [
    ("Política estándar", politica),
    ("Política más corta", politica_mas_corta),
    ("Política sin símbolo obligatorio", politica_sin_simbolo),
    ("Política imposible", politica_imposible)
]

for nombre, pol in casos_guardianpass:
    print("=" * 60)
    print(nombre)
    soluciones, stats = generar_contrasenas(pol, limite=5)

    print("Soluciones encontradas:", soluciones)
    print("Cantidad:", len(soluciones))
    print("Estadísticas:", stats)
    print()

"""## 6. Lo que este ejemplo enseña

GuardianPass muestra una forma básica de backtracking:

1. construir una solución parcial;
2. probar candidatos;
3. verificar restricciones;
4. podar ramas imposibles;
5. retroceder para probar otras opciones.

Este ejemplo es útil para proyectos donde la solución se construye como una lista: contraseñas, combinaciones de variables, roles, muestras, asignaciones o configuraciones.

# Parte II — ROVER-5  
## Encontrar un camino en una grilla con obstáculos

Ahora veremos un ejemplo visual. ROVER-5 es un robot virtual que debe llegar desde `S` hasta `G`.

El robot puede moverse arriba, abajo, izquierda o derecha. Debe evitar obstáculos `#` y no repetir celdas en el mismo camino.

## 7. Modelamiento con backtracking

| Elemento | En ROVER-5 |
|---|---|
| Solución parcial | Camino recorrido hasta el momento |
| Candidatos | Movimientos arriba, abajo, izquierda, derecha |
| Restricciones | No salir de la grilla, no pisar obstáculos, no repetir celdas |
| Solución completa | La posición actual es la meta |
| Retroceso | Deshacer el último movimiento si lleva a un callejón sin salida |
| Poda | Evitar celdas repetidas; opcionalmente usar energía o distancia |

Este ejemplo es útil para proyectos con matrices, grillas, mapas, laberintos o planificación.

## 8. Datos de ejemplo de ROVER-5

Usaremos tres grillas:

1. una con solución;
2. una sin solución;
3. una con varios caminos posibles.
"""

grilla_con_solucion = [
    ["S", ".", ".", "#", "."],
    ["#", "#", ".", "#", "."],
    [".", ".", ".", ".", "."],
    [".", "#", "#", "#", "."],
    [".", ".", ".", ".", "G"]
]

grilla_sin_solucion = [
    ["S", ".", "#", ".", "."],
    ["#", ".", "#", ".", "#"],
    [".", ".", "#", ".", "."],
    [".", "#", "#", "#", "."],
    [".", ".", ".", "#", "G"]
]

grilla_varios_caminos = [
    ["S", ".", ".", ".", "."],
    [".", "#", "#", "#", "."],
    [".", ".", ".", ".", "."],
    [".", "#", ".", "#", "."],
    [".", ".", ".", "#", "G"]
]

"""## 9. Funciones auxiliares para grillas

Estas funciones buscan posiciones, imprimen grillas y calculan vecinos.

"""

def imprimir_grilla(grilla):
    for fila in grilla:
        print(" ".join(fila))

def copiar_grilla(grilla):
    return [fila[:] for fila in grilla]

def buscar_posicion(grilla, simbolo):
    for i in range(len(grilla)):
        for j in range(len(grilla[0])):
            if grilla[i][j] == simbolo:
                return (i, j)
    return None

def distancia_manhattan(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def obtener_candidatos_rover(posicion):
    fila, columna = posicion

    movimientos = [
        (-1, 0),  # arriba
        (1, 0),   # abajo
        (0, -1),  # izquierda
        (0, 1)    # derecha
    ]

    candidatos = []
    for df, dc in movimientos:
        candidatos.append((fila + df, columna + dc))

    return candidatos

def esta_dentro(grilla, posicion):
    fila, columna = posicion
    return 0 <= fila < len(grilla) and 0 <= columna < len(grilla[0])

def es_valido_rover(grilla, posicion, visitados):
    if not esta_dentro(grilla, posicion):
        return False

    fila, columna = posicion

    if grilla[fila][columna] == "#":
        return False

    if posicion in visitados:
        return False

    return True

print("Grilla con solución:")
imprimir_grilla(grilla_con_solucion)
print("Inicio:", buscar_posicion(grilla_con_solucion, "S"))
print("Meta:", buscar_posicion(grilla_con_solucion, "G"))

"""## 10. Backtracking para ROVER-5

La función intentará encontrar un camino desde `S` hasta `G`.

También usará contadores:

- llamadas recursivas;
- ramas descartadas;
- retrocesos.

La poda opcional usa energía: si la distancia Manhattan a la meta es mayor que la energía restante, no se sigue por esa rama.

"""

def resolver_rover(grilla, usar_poda=True, energia_maxima=None):
    inicio = buscar_posicion(grilla, "S")
    meta = buscar_posicion(grilla, "G")

    if inicio is None or meta is None:
        raise ValueError("La grilla debe tener un inicio S y una meta G.")

    camino = [inicio]
    visitados = {inicio}

    estadisticas = {
        "llamadas_recursivas": 0,
        "ramas_descartadas": 0,
        "retrocesos": 0
    }

    def backtracking(posicion_actual, energia_restante):
        estadisticas["llamadas_recursivas"] += 1

        # Caso base: llegamos a la meta.
        if posicion_actual == meta:
            return True

        for candidato in obtener_candidatos_rover(posicion_actual):

            if not es_valido_rover(grilla, candidato, visitados):
                estadisticas["ramas_descartadas"] += 1
                continue

            # Poda opcional por energía y distancia mínima.
            if usar_poda and energia_restante is not None:
                energia_despues = energia_restante - 1

                if energia_despues < 0:
                    estadisticas["ramas_descartadas"] += 1
                    continue

                if distancia_manhattan(candidato, meta) > energia_despues:
                    estadisticas["ramas_descartadas"] += 1
                    continue
            else:
                energia_despues = None if energia_restante is None else energia_restante - 1

            # Tomar decisión.
            camino.append(candidato)
            visitados.add(candidato)

            if backtracking(candidato, energia_despues):
                return True

            # Retroceso.
            camino.pop()
            visitados.remove(candidato)
            estadisticas["retrocesos"] += 1

        return False

    encontrado = backtracking(inicio, energia_maxima)
    return encontrado, camino, estadisticas

"""## 11. Visualización de la solución

Marcamos el camino encontrado con `*`.

"""

def grilla_con_camino(grilla, camino):
    nueva = copiar_grilla(grilla)

    for fila, columna in camino:
        if nueva[fila][columna] not in ("S", "G"):
            nueva[fila][columna] = "*"

    return nueva


encontrado, camino, stats = resolver_rover(
    grilla_con_solucion,
    usar_poda=True,
    energia_maxima=12
)

print("¿Se encontró camino?", encontrado)
print("Camino:", camino)
print("Estadísticas:", stats)

print("\nSolución:")
imprimir_grilla(grilla_con_camino(grilla_con_solucion, camino))

"""## 12. Pruebas de ROVER-5

Probamos tres tipos de caso.

"""

casos_rover = [
    ("Caso con solución", grilla_con_solucion, 12),
    ("Caso sin solución", grilla_sin_solucion, 12),
    ("Caso con varios caminos", grilla_varios_caminos, 14)
]

for nombre, grilla, energia in casos_rover:
    print("=" * 60)
    print(nombre)
    print("Grilla inicial:")
    imprimir_grilla(grilla)

    encontrado, camino, stats = resolver_rover(
        grilla,
        usar_poda=True,
        energia_maxima=energia
    )

    print("\n¿Se encontró camino?", encontrado)
    print("Estadísticas:", stats)

    if encontrado:
        print("Camino encontrado:")
        imprimir_grilla(grilla_con_camino(grilla, camino))
    else:
        print("No existe camino bajo las condiciones dadas.")

    print()

"""## 13. Comparación breve: con poda y sin poda

La poda no cambia el significado del problema. Solo evita explorar ramas que ya no pueden servir.

En este ejemplo, la poda usa energía y distancia Manhattan.

"""

print("Comparación en grilla con varios caminos\n")

encontrado_poda, camino_poda, stats_poda = resolver_rover(
    grilla_varios_caminos,
    usar_poda=True,
    energia_maxima=14
)

encontrado_sin_poda, camino_sin_poda, stats_sin_poda = resolver_rover(
    grilla_varios_caminos,
    usar_poda=False,
    energia_maxima=14
)

print("Con poda:")
print(stats_poda)

print("\nSin poda:")
print(stats_sin_poda)

print("\nNota: los números pueden cambiar si se modifica el orden de movimientos.")

"""# Parte III — Cómo adaptar esta plantilla a otro proyecto

Los dos ejemplos anteriores tienen formas distintas:

- GuardianPass construye una **lista de caracteres**.
- ROVER-5 construye un **camino en una matriz**.

Pero ambos siguen el mismo esquema.

## 14. Plantilla general de backtracking

```python
def es_solucion_completa(estado):
    pass

def obtener_candidatos(estado):
    pass

def es_valido(estado, candidato):
    pass

def puede_podar(estado):
    pass

def backtracking(estado):
    if es_solucion_completa(estado):
        return estado

    for candidato in obtener_candidatos(estado):
        if es_valido(estado, candidato):
            aplicar_candidato(estado, candidato)

            if not puede_podar(estado):
                resultado = backtracking(estado)
                if resultado:
                    return resultado

            deshacer_candidato(estado, candidato)

    return None
```

No tienen que copiar exactamente estos nombres. Lo importante es que puedan explicar qué significa cada parte en su proyecto.

## 15. Cómo adaptar esta plantilla a mi proyecto

Para su proyecto propio deben definir:

- **Estado:** qué representa una solución parcial.
  - Contraseña parcial, camino parcial, asignación de roles, muestra seleccionada, colores de un grafo, etc.

- **Candidatos:** qué opciones se prueban en cada paso.
  - Caracteres, movimientos, usuarios, variables, franjas, valores de verdad, etc.

- **Restricciones:** qué hace que una opción sea válida o inválida.
  - No repetir, no chocar, no exceder presupuesto, cumplir cuotas, no violar una cláusula.

- **Solución completa:** cuándo se terminó con éxito.
  - Contraseña completa, llegada a la meta, todos los cursos coloreados, fórmula satisfecha.

- **Poda:** qué permite descartar ramas antes de terminarlas.
  - Falta de posiciones, presupuesto superado, cuota imposible, cláusula falsa, distancia mayor que energía.

- **Visualización:** cómo mostrar el resultado.
  - Tabla, matriz, gráfica, lista de soluciones o resumen de estadísticas.

## 16. Preguntas de reflexión

Respondan estas preguntas en su proyecto:

1. ¿Cuál fue la representación elegida para la solución parcial?
2. ¿Qué candidatos prueba el algoritmo?
3. ¿Cuál fue la restricción más importante?
4. ¿Dónde ocurre el retroceso en el código?
5. ¿Qué poda implementaron?
6. ¿Qué caso de prueba falló inicialmente?
7. ¿Qué cambiarían si el problema fuera más grande?
8. ¿El algoritmo encuentra una solución, todas las soluciones o la mejor solución?

## 17. Checklist para el proyecto propio

Antes de entregar, verifiquen:

- [ ] El notebook corre desde cero.
- [ ] El problema está explicado con una historia breve.
- [ ] La representación de datos es clara.
- [ ] Hay una función de restricciones.
- [ ] Hay una función principal de backtracking.
- [ ] Se reportan llamadas recursivas.
- [ ] Se reportan ramas descartadas.
- [ ] Se reportan retrocesos.
- [ ] Hay al menos tres casos de prueba.
- [ ] Hay un ejemplo manual pequeño.
- [ ] El README explica cómo ejecutar el proyecto.
- [ ] El informe tiene sección de decisiones del grupo.
- [ ] Cada integrante puede explicar una parte del código.
"""